In [1]:
import pandas as pd
import pickle
from gop import *
from utils import *
from scipy.special import softmax
from kaldiio import ReadHelper
import tqdm

In [15]:
generate_df_phones_pure()
generate_df_alignments()

364it [00:00, 206035.99it/s]
42it [00:00, 160291.87it/s]
346it [00:00, 172048.51it/s]

In [11]:
df_phones_pure = pd.read_pickle('phones_pure_epa.pickle')
df_phones_pure = df_phones_pure.reset_index()
df_phones_pure

,phone,phone_name,transition_state,hmm_state,forward_pdf,self_pdf,transition_id,phone_pure,phone_pure_name
0,15,AA0_B,263,0,2,4326,525,3,AA
1,15,AA0_B,263,0,2,4326,526,3,AA
2,15,AA0_B,264,0,225,4324,527,3,AA
3,15,AA0_B,264,0,225,4324,528,3,AA
4,15,AA0_B,265,0,225,4392,529,3,AA
...,...,...,...,...,...,...,...,...,...
43985,342,Z_S,21935,0,5996,5863,43870,40,Z
43986,342,Z_S,21936,0,5996,5949,43871,40,Z
43987,342,Z_S,21936,0,5996,5949,43872,40,Z
43988,342,Z_S,21937,0,5996,6008,43873,40,Z
43989,342,Z_S,21937,0,5996,6008,43874,40,Z

In [14]:
alignments = pd.read_pickle('alignments.pickle')
alignments
#alignments = pd.DataFrame.from_dict(alignments)
#alignments

#pd.DataFrame(alignments.loc[:,'spkr32_58']).transpose()

{}

In [6]:
gop = {}
with ReadHelper('ark:loglikes.ark') as reader:
    for key, loglikes in tqdm.tqdm(reader):
        
        loglikes = softmax(np.array(loglikes), axis=1)
        df_scores = pd.DataFrame(alignments.loc[:,key]).transpose()
        df_scores['p'] = [loglikes]
        gop[key] = gop_robust_with_matrix(df_scores, df_phones_pure, 6024, 1, [], [])

with open('gop_epa.pickle', 'wb') as handle:
    pickle.dump(gop, handle, protocol=pickle.HIGHEST_PROTOCOL)

1904it [15:58,  1.99it/s]

In [7]:
gop_epa = pd.read_pickle('gop_epa.pickle')

In [8]:
gop_output_file = open('gop_epa.txt', 'w+')

for logid, score in gop_epa.items():
    score = score[0]
    #print(score)
    phones = score['phones_pure']
    gop = score['gop']
    
    if len(phones) != len(gop):
        raise Exception("Phones and gop list lengths do not match.")
    
    gop_output_file.write(logid)
    for i in range(len(phones)):
        gop_output_file.write(' [ ' + phones[i] + ' ' + str(gop[i]) + ' ] ')
    gop_output_file.write('\n')

In [20]:
df_phones_pure

,phone,phone_name,transition_state,hmm_state,pdf,transition_id,phone_pure,phone_pure_name
0,15,AA0_B,263,0,2,525,3,AA
1,15,AA0_B,263,0,2,526,3,AA
2,15,AA0_B,264,0,225,527,3,AA
3,15,AA0_B,264,0,225,528,3,AA
4,15,AA0_B,265,0,225,529,3,AA
...,...,...,...,...,...,...,...,...
43985,342,Z_S,21935,0,5996,43870,40,Z
43986,342,Z_S,21936,0,5996,43871,40,Z
43987,342,Z_S,21936,0,5996,43872,40,Z
43988,342,Z_S,21937,0,5996,43873,40,Z
43989,342,Z_S,21937,0,5996,43874,40,Z

In [17]:
pdfs = [int(x) for x in list(df_phones_pure.pdf.unique())]
pdfs.sort()
pdfs

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 43,
 44,
 45,
 47,
 55,
 56,
 58,
 59,
 63,
 64,
 72,
 74,
 77,
 78,
 86,
 88,
 92,
 93,
 96,
 102,
 103,
 105,
 107,
 108,
 110,
 111,
 112,
 113,
 116,
 117,
 119,
 120,
 122,
 124,
 125,
 129,
 131,
 132,
 135,
 139,
 140,
 141,
 144,
 146,
 147,
 150,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 175,
 178,
 179,
 180,
 185,
 189,
 192,
 193,
 194,
 196,
 197,
 199,
 201,
 202,
 203,
 205,
 207,
 209,
 210,
 212,
 214,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 230,
 231,
 233,
 235,
 236,
 238,
 239,
 242,
 244,
 245,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 258,
 261,
 262,
 263,
 264,
 266,
 268,
 269,
 271,
 272,
 273,
 274,
 277,
 278,
 280,
 282,
 283,
 284,
 285,
 287,
 288,
 289,
 290,
 294,
 295,
 296,
 297,
 299,
 301,
 302,
 303,
 304,
 305,
 307,
 309,
 310,
 311,
 314,
 317,
 318,
 319,
 321,
 323,
 324,
 325,
 326,
 327,
 330,
 333,
 334,
 336,
 337,
 339,
 342,
 343,
 344,
 345,
 347,
 348,
 349,
 356,
 357,
 359,
 361,
 362,
 363,
 364,
 365,
 368,
 369,
 372,
 375,
 377,
 379,
 382,
 383,
 385,
 386,
 387,
 388,
 391,
 395,
 398,
 400,
 401,
 404,
 407,
 408,
 413,
 414,
 415,
 416,
 421,
 422,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 434,
 435,
 437,
 440,
 445,
 447,
 449,
 450,
 451,
 452,
 453,
 454,
 456,
 457,
 460,
 461,
 463,
 465,
 467,
 468,
 471,
 473,
 474,
 479,
 480,
 481,
 483,
 484,
 486,
 487,
 492,
 493,
 494,
 496,
 497,
 499,
 501,
 503,
 508,
 509,
 510,
 513,
 515,
 519,
 520,
 523,
 524,
 527,
 528,
 529,
 530,
 531,
 533,
 534,
 540,
 541,
 542,
 543,
 547,
 550,
 551,
 559,
 560,
 562,
 563,
 564,
 568,
 570,
 572,
 573,
 575,
 576,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 588,
 589,
 590,
 591,
 593,
 594,
 597,
 601,
 603,
 605,
 606,
 607,
 608,
 611,
 613,
 614,
 615,
 616,
 617,
 627,
 630,
 631,
 632,
 634,
 636,
 637,
 645,
 647,
 651,
 652,
 653,
 655,
 657,
 662,
 663,
 664,
 667,
 668,
 669,
 671,
 673,
 674,
 675,
 676,
 677,
 685,
 686,
 692,
 693,
 695,
 700,
 702,
 704,
 705,
 706,
 708,
 712,
 713,
 714,
 715,
 717,
 718,
 720,
 722,
 723,
 724,
 729,
 732,
 733,
 734,
 737,
 738,
 739,
 741,
 743,
 745,
 746,
 747,
 750,
 751,
 752,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 764,
 765,
 767,
 768,
 769,
 773,
 775,
 777,
 778,
 780,
 783,
 784,
 785,
 787,
 789,
 791,
 794,
 797,
 798,
 799,
 801,
 806,
 807,
 809,
 813,
 815,
 816,
 817,
 818,
 820,
 821,
 823,
 824,
 825,
 828,
 833,
 836,
 838,
 841,
 842,
 843,
 846,
 847,
 848,
 849,
 859,
 860,
 861,
 862,
 867,
 868,
 870,
 871,
 878,
 879,
 882,
 888,
 896,
 897,
 905,
 906,
 909,
 910,
 912,
 913,
 915,
 916,
 918,
 919,
 926,
 928,
 934,
 935,
 938,
 941,
 942,
 944,
 948,
 950,
 951,
 952,
 954,
 955,
 961,
 962,
 963,
 966,
 969,
 970,
 971,
 972,
 973,
 975,
 976,
 977,
 980,
 984,
 985,
 986,
 987,
 992,
 993,
 994,
 995,
 998,
 1000,
 1001,
 1002,
 1004,
 1009,
 1010,
 1011,
 1014,
 1019,
 1021,
 1023,
 1024,
 1025,
 1029,
 1030,
 1032,
 1033,
 1035,
 1036,
 1037,
 1038,
 1040,
 1041,
 1042,
 1046,
 1047,
 1048,
 1049,
 1051,
 1053,
 1055,
 1056,
 1057,
 1060,
 1062,
 1065,
 1066,
 1070,
 1074,
 1075,
 1077,
 1080,
 1081,
 1082,
 1085,
 1087,
 1088,
 1093,
 1095,
 1097,
 1098,
 1099,
 1101,
 1102,
 1103,
 1104,
 1106,
 1108,
 1109,
 1111,
 1112,
 1113,
 1118,
 1120,
 1121,
 1123,
 1125,
 1128,
 1129,
 1131,
 1134,
 1135,
 1138,
 1140,
 1147,
 1149,
 1151,
 1155,
 1161,
 1162,
 1163,
 1165,
 1167,
 1172,
 1173,
 1176,
 1181,
 1184,
 1187,
 1188,
 1192,
 1194,
 1197,
 1198,
 1199,
 1200,
 1204,
 1205,
 1208,
 1209,
 1210,
 1211,
 1214,
 1216,
 1217,
 1218,
 1220,
 1222,
 1223,
 1226,
 1229,
 1230,
 1231,
 1232,
 1234,
 1238,
 1239,
 1240,
 1242,
 1243,
 1246,
 1248,
 1249,
 1252,
 1254,
 1255,
 1258,
 1259,
 1260,
 1262,
 1263,
 1264,
 1266,
 1268,
 1270,
 1271,
 1272,
 1273,
 1276,
 1280,
 1290,
 1292,
 1296,
 1297,
 1298,
 1304,
 1306,
 1307,
 1308,
 1309,
 1311,
 1317,
 1318,
 1320,
 1321,
 1322,
 1325,
 1327,
 1329,
 1330,
 1332,
 1333,
 1335,
 1337,
 1338,
 1339,
 1341,
 1343,
 1350,
 1351,
 1352,
 1355,
 1356,
 1357,
 1358,
 1361,
 1362,
 1363,
 1364,
 1367,
 1369,
 1370,
 1371,
 1373,
 1374,
 1376,
 1377,
 1380,
 1381,
 1382,
 1384,
 1387,
 1388,
 1390,
 1391,
 1392,
 1396,
 1401,
 1403,
 1404,
 1407,
 1411,
 1414,
 1416,
 1420,
 1422,
 1423,
 1424,
 1425,
 1428,
 1429,
 1430,
 1431,
 1433,
 1435,
 1436,
 1437,
 1440,
 1442,
 1448,
 1449,
 1452,
 1453,
 1454,
 1455,
 1456,
 1458,
 1459,
 1461,
 1462,
 1463,
 1465,
 1466,
 1467,
 1468,
 1469,
 1472,
 1473,
 1476,
 1477,
 1479,
 1480,
 1481,
 1482,
 1484,
 1485,
 1486,
 1487,
 1488,
 1490,
 1491,
 1492,
 1494,
 1496,
 1497,
 1498,
 1499,
 1500,
 1501,
 1506,
 1509,
 1512,
 1513,
 1516,
 1519,
 1521,
 1523,
 1524,
 1526,
 1530,
 1531,
 1532,
 1536,
 1537,
 1538,
 1541,
 1543,
 1544,
 1545,
 1547,
 1548,
 1549,
 1553,
 1555,
 1557,
 1559,
 1567,
 1570,
 1572,
 1580,
 1581,
 1586,
 1587,
 1589,
 1592,
 1593,
 1594,
 1597,
 1598,
 1601,
 1605,
 1607,
 1609,
 1611,
 1613,
 1616,
 1617,
 1618,
 1620,
 1623,
 1624,
 1625,
 1627,
 1630,
 1631,
 1634,
 1638,
 1640,
 1642,
 1643,
 1645,
 1646,
 1649,
 1651,
 1654,
 1655,
 1657,
 1661,
 1662,
 1663,
 1666,
 1667,
 1669,
 1673,
 1676,
 1681,
 1683,
 1684,
 1686,
 1688,
 1692,
 1694,
 1695,
 1696,
 1698,
 1704,
 1705,
 1706,
 1707,
 1709,
 1710,
 1711,
 1714,
 1715,
 1719,
 1720,
 1727,
 1734,
 1737,
 1739,
 1740,
 1743,
 1744,
 1745,
 1747,
 1753,
 1754,
 1756,
 1761,
 1763,
 1765,
 1768,
 1769,
 1771,
 1773,
 1778,
 1779,
 1781,
 1786,
 1787,
 1792,
 1793,
 1795,
 1805,
 1806,
 1807,
 1810,
 1811,
 1812,
 1815,
 1817,
 1818,
 1819,
 1820,
 1821,
 1823,
 1825,
 1827,
 1829,
 1830,
 1831,
 1833,
 1836,
 1837,
 1838,
 1840,
 1841,
 1850,
 1854,
 1855,
 1857,
 1859,
 1860,
 1865,
 1866,
 1867,
 1870,
 1872,
 1873,
 1874,
 1877,
 1878,
 1879,
 1880,
 1883,
 1889,
 1892,
 1893,
 1894,
 1895,
 1896,
 1897,
 1898,
 1900,
 1902,
 1903,
 1906,
 1910,
 1911,
 1912,
 1915,
 1916,
 1917,
 1918,
 1920,
 1921,
 1923,
 1926,
 1927,
 1928,
 1930,
 1932,
 1935,
 1937,
 1940,
 1942,
 1943,
 1947,
 1949,
 1950,
 1951,
 1952,
 1953,
 1956,
 1957,
 1960,
 1961,
 ...]

In [19]:
df_phones_pure.loc[(df_phones_pure['phone_pure'] == str(2) )].pdf.unique()

array(['1'], dtype=object)